version: '3'

services:
  postgres-db:
    image: postgres:16.2
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_MYSQL}
      MYSQL_DATABASE: ${DB_NAME_MYSQL}
    ports:
      - '${DB_PORT_MYSQL}:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data: